# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.8.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.runtime_raw_extension import RuntimeRawExtension  # noqa: E501
from kubernetes.client.rest import ApiException


class TestRuntimeRawExtension(unittest.TestCase):
    """RuntimeRawExtension unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuntimeRawExtension(self):
        """Test RuntimeRawExtension"""
        # FIXME: construct object with mandatory attributes with example values
        # model = client.models.runtime_raw_extension.RuntimeRawExtension()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
