# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.8.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1beta1_host_port_range import V1beta1HostPortRange  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1beta1HostPortRange(unittest.TestCase):
    """V1beta1HostPortRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1HostPortRange(self):
        """Test V1beta1HostPortRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = client.models.v1beta1_host_port_range.V1beta1HostPortRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
