# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.8.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1alpha1_rule_with_operations import V1alpha1RuleWithOperations  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1alpha1RuleWithOperations(unittest.TestCase):
    """V1alpha1RuleWithOperations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1RuleWithOperations(self):
        """Test V1alpha1RuleWithOperations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1alpha1_rule_with_operations.V1alpha1RuleWithOperations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
